<?php

declare(strict_types = 1);

/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\ComposerUtils\Service\NamespaceService\SubObject;

use Constup\Automatrix\LanguagePhp\Version0702\DesignPatternInterfaces\ValidatorInterface;

interface NamespaceValidatorInterface extends ValidatorInterface
{
    /**
     * @param string $namespace
     *
     * @return self
     */
    public function validateNamespace(string $namespace): self;

    /**
     * @param string $absoluteDirectory
     *
     * @return self
     */
    public function validateAbsoluteDirectory(string $absoluteDirectory): self;

    /**
     * @param NamespaceImmutableObjectInterface $object
     *
     * @return NamespaceValidatorInterface
     */
    public function validateObject(NamespaceImmutableObjectInterface $object): self;
}
