<?php

declare(strict_types = 1);
/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\ComposerUtils\Service\NamespaceService\SubObject;

use Constup\Automatrix\LanguagePhp\Version0702\DesignPatternInterfaces\ValidatorInterface;

class NamespaceValidator implements ValidatorInterface, NamespaceValidatorInterface
{
    /**
     * @param string $namespace
     *
     * @return self
     */
    public function validateNamespace(string $namespace): NamespaceValidatorInterface
    {
        return $this;
    }

    /**
     * @param string $absoluteDirectory
     *
     * @return self
     */
    public function validateAbsoluteDirectory(string $absoluteDirectory): NamespaceValidatorInterface
    {
        return $this;
    }

    /**
     * @param NamespaceImmutableObjectInterface $object
     *
     * @return NamespaceValidatorInterface
     */
    public function validateObject(NamespaceImmutableObjectInterface $object): NamespaceValidatorInterface
    {
        return $this->validateNamespace($object->getNamespace())
                    ->validateAbsoluteDirectory($object->getAbsoluteDirectory());
    }
}
