<?php

declare(strict_types = 1);

/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\ComposerUtils\Service\NamespaceService\SubObject;

use Constup\Automatrix\LanguagePhp\Version0702\DesignPatternInterfaces\ImmutableObjectInterface;

interface NamespaceImmutableObjectInterface extends ImmutableObjectInterface
{
    /**
     * @return string
     * @codeCoverageIgnore
     */
    public function getNamespace(): string;

    /**
     * @param string $namespace
     *
     * @return NamespaceImmutableObject
     */
    public function withNamespace(string $namespace): self;

    /**
     * @return string
     * @codeCoverageIgnore
     */
    public function getAbsoluteDirectory(): string;

    /**
     * @param string $absoluteDirectory
     *
     * @return NamespaceImmutableObject
     */
    public function withAbsoluteDirectory(string $absoluteDirectory): self;
}
