<?php

declare(strict_types = 1);
/**
 * This file has been automatically generated by Constup Automatrix.
 * https://constup.com/automatrix
 */

namespace Constup\ComposerUtils\Tests\Service\NamespaceService\SubObject;

trait NamespaceTestDataProviderTrait
{
    public function testHasPropertiesDataProvider()
    {
        /**
         * You are free to populate this data provider with sample data.
         * If you try to run any command which re-generates this file, the contents of this
         * method will be copied to the same method in the newly generated file.
         *
         * Which means - you are free to experiment, re-generate and/or run any Automatrix generator command
         * without any fear that your data entered here will be lost.
         */
    }

    public function testWithNamespaceDataProvider()
    {
        /**
         * You are free to populate this data provider with sample data.
         * If you try to run any command which re-generates this file, the contents of this
         * method will be copied to the same method in the newly generated file.
         *
         * Which means - you are free to experiment, re-generate and/or run any Automatrix generator command
         * without any fear that your data entered here will be lost.
         */
    }

    public function testWithAbsoluteDirectoryDataProvider()
    {
        /**
         * You are free to populate this data provider with sample data.
         * If you try to run any command which re-generates this file, the contents of this
         * method will be copied to the same method in the newly generated file.
         *
         * Which means - you are free to experiment, re-generate and/or run any Automatrix generator command
         * without any fear that your data entered here will be lost.
         */
    }
}
